TTOON/Config/Dev.xcconfig, TTOON/Config/Prod.xcconfig, TTOON/Config/Stag.xcconfig
리뷰 부탁드립니다😀
[문서](https://www.notion.so/lyoodong/TTOON-48-694a3db3352749a78e946b79e94c0b11?pvs=4)
=> [TN-48] 빌드 환경 분리 및 환경 변수 설정

.github/workflows/assign-reviewer.yml, .swiftlint.yml, TTOON.xcodeproj/project.pbxproj
Issue Number: TTOON-62
[[문서]](https://www.notion.so/lyoodong/TTOON-62-SwiftLint-cde80d815ad4443b91305a0df8dcf1dc)
- 빌드 마다 코드를 Linting 해주는 SwiftLint를 추가했습니다.
- 기본 룰은 많이 사용하는 것들로 추가했고, 필요하시면 추가 혹은 삭제 가능합니다.
- SwiftLint 설치 안되어 있는 경우에, 문서 참고하셔서 설치 후 빌드하시면 잘 돌아갈겁니다!
=> [TN-62] SwiftLint 설치

TTOON.xcodeproj/project.pbxproj, TTOON/Data/API/Auth/LoginAPI.swift, TTOON/Data/DataMapping/Auth/AuthDTO.swift, TTOON/Data/DataMapping/Common/ResponseDTO.swift, TTOON/Data/Repository/Auth/LoginRepository.swift, TTOON/Domain/Entity/Auth/LoginResponseModel.swift, TTOON/Domain/Interface/Repository/Auth/LoginRepositoryProtocol.swift, TTOON/Domain/UseCase/Auth/LoginUseCase.swift, TTOON/Presentation/Auth/ViewModel/LoginViewModel.swift
Issue Number: TTOON-131
- Login API 구현 (추후 Splash API와 통합하여 Auth API 하나로 만드는 게 좋을 것 같습니다)
- 소셜 로그인 플랫폼 (애플, 카카오, 구글) 과의 통신 결과를 이용해서 TTOON 서버 통신 구현
- Entity Model과 Data DTO를 따로 생성하여, 레이어 별 사용하는 구조체를 분리하였습니다.
- 네트워크 통신 결과를 Repository -> UseCase -> ViewModel로 전달하는 과정에서 코드가 가독성이 좋지 않을 수 있습니다. 궁금하신 점 있으시면 답변 드리겠습니다.
- 통신 결과를 이용해서 따로 동작하도록 구현한 기능은 없습니다. 추후 Coordinator 이용해서 Splash -> Login -> 다음 화면 연결하는 작업에서 진행하면 될 것 같습니다.
- 각 파일들의 폴더링 확인해주세요. 아무래도 많은 파일들이 생성될 것 같아서 기본적으로 Auth 폴더 내에 파일 생성하였습니다.
=> [TN-131] 소셜 로그인 네트워크 연결

TTOON.xcodeproj/project.pbxproj, TTOON.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, TTOON/Application/SceneDelegate.swift, TTOON/Presentation/CustomView/Toon/CreateToon/CreateToonCollectionView.swift, TTOON/Presentation/CustomView/Toon/CreateToon/CreateToonCollectionViewCell.swift, TTOON/Presentation/Toon/CreateToon/View/SelectStyleView.swift, TTOON/Presentation/Toon/CreateToon/ViewController/SelectStyleViewController.swift, TTOON/Presentation/Toon/CreateToon/ViewModel/SelectStyleReactor.swift, TTOON/Util/Extension/UICollectionView+.swift
Issue Number: TTOON- 167
[**문서**](https://www.notion.so/lyoodong/iOS-f2404d824186417c9d8842e24d8ec528?p=38961fb4b2ee4b60aee4e101a0d33359&pm=s)
- 그림체 선택화면 UI 작업입니다. 
- 현재 탭바가 별도로 없는듯 보여 임시로 SceneDelegate에서 로딩화면을 변경했습니다.
- `SelectStyleView`, `SelectStyleViewController`, `SelectStyleReactor` 중심으로 봐주시면 감사하겠습니다!
- 문서에 첨부했습니다.
=>  [SUB] 그림체 스타일 선택 UI 작업

TTOON.xcodeproj/project.pbxproj, TTOON.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, TTOON/Application/AppCoordinator.swift, TTOON/Presentation/Auth/Coordinator/AuthCoordinator.swift, TTOON/Presentation/Auth/Splash/ViewController/SplashViewController.swift, TTOON/Presentation/Home/Coordinator/TabBarCoordinator.swift, TTOON/Presentation/Setting/Coordinator/SettingCoordinator.swift, TTOON/Util/Base/Coordinator.swift
=> [NO-ISSUE] 스플레시 로딩 타임 및 메인 화면 진입 로직 추가 

TTOON/Application/AppCoordinator.swift, TTOON/Presentation/Auth/Coordinator/AuthCoordinator.swift, TTOON/Presentation/Auth/Login/ViewController/LoginViewController.swift, TTOON/Presentation/Auth/Login/ViewModel/LoginViewModel.swift, TTOON/Presentation/Home/Calendar/Coordinator/CalendarSceneCoordinator.swift, TTOON/Presentation/Home/Calendar/View/Cell/TToonCalendarCell.swift, TTOON/Presentation/Home/Feed/Coordinator/FeedSceneCoordinator.swift, TTOON/Presentation/Setting/Coordinator/MyPageSceneCoordinator.swift, TTOON/Presentation/Setting/Coordinator/SettingCoordinator.swift, TTOON/Presentation/Tabbar/TabBarCoordinator.swift, TTOON/Util/Base/Coordinator.swift, TTOON/Util/Constant/TNImage.swift
- Auth, TabBar 코디네이터 패턴 적용 완료했습니다.
- TabBar 코디의 자식 코디들 (Calendar, Feed, Attendance, MyPage)도 만들어 두었고, 아직 해당 코디 내에서의 화면 전환 로직은 없습니다.
=> [NO-ISSUE] Auth, TabBar 코디네이터 패턴 적용

TTOON/Application/SceneDelegate.swift, TTOON/Data/API/Auth/LoginAPI.swift, TTOON/Data/API/Setting/SettingAPI.swift, TTOON/Data/DTO/Auth/AuthDTO.swift, TTOON/Data/Repository/Setting/MyPageRepository.swift, TTOON/Network/AuthInterceptor.swift, TTOON/Presentation/Auth/Coordinator/AuthCoordinator.swift, TTOON/Presentation/Auth/Splash/ViewModel/SplashErrorReactor.swift, TTOON/Presentation/Auth/Splash/ViewModel/SplashReactor.swift, TTOON/Presentation/Setting/MyPage/ViewController/MyPageViewController.swift
Issue Number: TTOON-197
- interceptor 구현
- setting API 수정해서 잘 동작하는 거 확인했습니다.
- 자세한 내용은 [문서](https://www.notion.so/lyoodong/TTOON-197-a578f783bd2b4d9bad135937f4825dd1)에 첨부했습니다. 코드에도 주석 남겨드렸습니다.
- X
=> [SUB] 인터 셉터 구현/ 자동 로그인/ 로그아웃

TTOON/Application/SceneDelegate.swift, TTOON/Data/API/Auth/LoginAPI.swift, TTOON/Data/API/Setting/SettingAPI.swift, TTOON/Data/DTO/Auth/AuthDTO.swift, TTOON/Data/Repository/Setting/MyPageRepository.swift, TTOON/Network/AuthInterceptor.swift, TTOON/Presentation/Auth/Coordinator/AuthCoordinator.swift, TTOON/Presentation/Auth/Splash/ViewModel/SplashErrorReactor.swift, TTOON/Presentation/Auth/Splash/ViewModel/SplashReactor.swift, TTOON/Presentation/Setting/MyPage/ViewController/MyPageViewController.swift
Issue Number: TTOON-197
- 메인에 머지할 PR
=> [TN-197] 인터셉터, 자동 로그인, 로그 아웃 구현

TTOON/Presentation/CustomView/Home/Calendar/SelectYearMonthView.swift, TTOON/Presentation/Home/Calendar/View/HomeCalendarView.swift, TTOON/Presentation/Home/Calendar/View/SubView/BottomDiaryView.swift, TTOON/Presentation/Home/Calendar/View/SubView/SelectYearMonthBottomSheetView.swift, TTOON/Presentation/Home/Calendar/ViewController/HomeCalendarViewController.swift, TTOON/Presentation/Home/Calendar/ViewController/SelectYearMonthBottomSheetViewController.swift, TTOON/Resource/Assets.xcassets/Home/arrow_down.imageset/Contents.json, TTOON/Resource/Assets.xcassets/Home/arrow_down.imageset/btn_arrow_smallarrow_bottom.svg
Issue Number: TTOON-177
- 일기 세부 화면 (Bottom Diary View)의 swipe collectionView 버그를 수정했습니다.
- [Carousel 구현 방법](https://ios-development.tistory.com/1020) 참고하였습니다.
- Carousel 컬렉션뷰와 PageControl 로직을 연결했습니다.
- 스크롤뷰의 높이를 설정하고, 불필요한 bounce를 해제하였습니다.
- 연월 선택 뷰의 구현 방식을 수정했습니다.
- sheetPresentVC 를 이용하여 자연스러운 UX를 구현했습니다. (추후 문의하기, 탈퇴하기에 있는 bottom sheet도 이와 같이 수정하겠습니다)
- 연월 선택 뷰에 위치한 chevron image를 수정하였습니다.
- "arrow_down" 이라는 이름으로 asset에 이미지 추가했습니다.
=> [TN-177] 캘린더 화면 UI 구현

TTOON.xcodeproj/project.pbxproj, TTOON/Data/API/Attendance/AttendanceAPI.swift, TTOON/Data/DTO/Attendance/AttendanceDTO.swift, TTOON/Data/Repository/Attendance/AttendanceRepository.swift, TTOON/Domain/Entity/Attendacne/AttendanceModel.swift, TTOON/Domain/Interface/Repository/Attendance/AttendanceRepositoryProtocol.swift, TTOON/Domain/UseCase/Attendance/AttendanceUseCase.swift, TTOON/Presentation/Attendance/View/AttendanceScrollView.swift, TTOON/Presentation/Attendance/View/AttendanceView.swift, TTOON/Presentation/Attendance/ViewController/AttendanceViewController.swift, TTOON/Presentation/Attendance/ViewModel/AttendanceReactor.swift, TTOON/Presentation/CustomView/Attendance/AttendanceNavigationBar.swift, TTOON/Presentation/Tabbar/TabBarCoordinator.swift, TTOON/Util/Enums/Common/DateFormatType.swift, TTOON/Util/Extension/Date+.swift, TTOON/Util/Extension/Observable+.swift, TTOON/Util/Extension/Single+.swift, TTOON/Util/Protocol/CommonError.swift
Issue Number: TTOON-200
- [**문서**](https://www.notion.so/lyoodong/TTOON-200-10910412f5978016b906e253fbf0f8fa) 첨부드립니다!
- '출석 체크 요청' 기능은 아직 API 개발이 미비되어서 명세서에 있는 스펙대로 구현만 해놓았습니다.(기능 테스트 불가)
- 기능 PR이라 없음
=> [TN-200] 출석체크 기능 구현

TTOON.xcodeproj/project.pbxproj, TTOON/Data/Keychain/KeychainStorage.swift, TTOON/Presentation/Setting/MyPage/View/AlarmView.swift, TTOON/Presentation/Setting/MyPage/View/MyPageChangeLangView.swift, TTOON/Presentation/Setting/MyPage/ViewController/AlarmViewController.swift, TTOON/Presentation/Setting/MyPage/ViewController/MyPageChangeLangViewController.swift, TTOON/Presentation/Setting/MyPage/ViewController/MyPageViewController.swift
- Eng -> ENG로 문구 변경
- 알림 설정 화면 제작
=> [FIX] 마이페이지 QA 내용 반영

TTOON/Presentation/CustomView/Toon/CreateToon/CreateToonDiaryView.swift, TTOON/Presentation/CustomView/Toon/CreateToon/CreateToonSelectCharactersButton.swift, TTOON/Presentation/Toon/CreateToon/View/EnterInfoScrollView.swift, TTOON/Presentation/Toon/CreateToon/View/EnterInfoView.swift, TTOON/Presentation/Toon/CreateToon/ViewController/CompleteToonViewController.swift, TTOON/Presentation/Toon/CreateToon/ViewController/CreateToonBaseViewController.swift, TTOON/Presentation/Toon/CreateToon/ViewController/EnterInfoViewController.swift, TTOON/Presentation/Toon/CreateToon/ViewModel/EnterInfoReactor.swift, TTOON/Util/Extension/UIColor+.swift, TTOON/Util/TNCompopnet/TextFiled/TNTextFiled.swift, TTOON/Util/TNCompopnet/TextFiled/TextStatusView.swift, TTOON/Util/TNCompopnet/TextFiled/innerTextField.swift
Issue Number: TTOON-210
- 프로그래스바 UI를 피그마 시안 형태로 변경했습니다.
- 동작 확인은 '일기 입력 텍스트뷰'를 입력할 경우, 프로그래스바가 변경되는 것을 확인하시면 좋을 것 같습니다.
- 데이터 바인딩은 동작 확인을 위해 '일기 입력 텍스트뷰'에만 바인딩 시켜놨습니다.
https://github.com/user-attachments/assets/1b6b8ecd-58c5-4685-976c-7e1a41420c7d
=> [TN-210] 생성 화면 프로그래스바 UI 수정

TTOON.xcodeproj/project.pbxproj, TTOON/Data/API/Home/Feed/FeedAPI.swift, TTOON/Data/DTO/CalendarFeed/FeedDTO.swift, TTOON/Data/Repository/Home/HomeFeedRepository.swift, TTOON/Domain/Entity/Friend/FriendModel.swift, TTOON/Domain/Entity/Home/FeedModel.swift, TTOON/Domain/UseCase/Home/HomeFeedUseCase.swift, TTOON/Presentation/CustomView/Home/Feed/FeedLikeButton.swift, TTOON/Presentation/Home/Feed/Coordinator/FeedSceneCoordinator.swift, TTOON/Presentation/Home/Feed/View/Cell/FeedTableViewCell.swift, TTOON/Presentation/Home/Feed/ViewController/HomeFeedViewController.swift, TTOON/Presentation/Home/Feed/ViewModel/HomeFeedReactor.swift, TTOON/Util/Extension/Reactive+.swift
Issue Number: TTOON-201
- 피드 화면에 필요한 네트워크 로직 구현하였습니다 (API, Repo, UseCase)
- 우선 피드 화면 API만을 이용해서, 피드 데이터를 응답받고 이를 화면에 보여주는 로직 구현하였습니다.
- "내 피드만 보기" Switch 제외 다른 사용자 액션은 아직 구현하지 않았습니다.
- 피드 정보 데이터를 제대로 응답받는지, 피드 tableView Cell에 제대로 적용되는지 확인해주시면 됩니다.
=> [TN-201] 피드 화면 로직 구현 - 1차

TTOON/Data/API/Home/Feed/FeedAPI.swift, TTOON/Data/Repository/Home/HomeFeedRepository.swift, TTOON/Domain/UseCase/Home/HomeFeedUseCase.swift, TTOON/Presentation/Home/Feed/View/Cell/FeedTableViewCell.swift, TTOON/Presentation/Home/Feed/ViewController/HomeFeedViewController.swift, TTOON/Presentation/Home/Feed/ViewModel/HomeFeedReactor.swift, TTOON/Presentation/Home/Friend/FriendList/ViewController/FriendListPopUpBottomSheetViewController.swift, TTOON/Presentation/Home/Friend/FriendList/ViewController/FriendListViewController.swift, TTOON/Presentation/Home/Friend/FriendList/ViewModel/FriendListReactor.swift, TTOON/Presentation/Home/Friend/Tabman/FriendTabViewController.swift, TTOON/Util/Extension/UIImageView+.swift
Issue Number: TTOON-201
- 바텀시트 구현하는 방식을 리뷰 주신 것처럼 모두 delegate 패턴으로 수정했습니다 (friendListVC, friendTabVC에 수정했습니다)
- 신고하기 구현했습니다. (문의하기 API 이용했습니다)
- 이미지 load 메서드 추가했습니다. (Kingfisher 활용)
=> [TN-201] 피드 화면 로직 구현 - 3차

TTOON/Data/API/Home/Feed/FeedAPI.swift, TTOON/Data/DTO/CalendarFeed/FeedDTO.swift, TTOON/Data/Repository/Home/HomeFeedRepository.swift, TTOON/Domain/Entity/Home/FeedModel.swift, TTOON/Domain/UseCase/Home/HomeFeedUseCase.swift, TTOON/Presentation/Home/Feed/View/Cell/FeedTableViewCell.swift, TTOON/Presentation/Home/Feed/ViewController/HomeFeedViewController.swift, TTOON/Presentation/Home/Feed/ViewModel/HomeFeedReactor.swift, TTOON/Presentation/Home/Friend/FriendList/ViewController/FriendListPopUpBottomSheetViewController.swift, TTOON/Presentation/Home/Friend/FriendList/ViewController/FriendListViewController.swift, TTOON/Presentation/Home/Friend/FriendList/ViewModel/FriendListReactor.swift, TTOON/Presentation/Home/Friend/Tabman/FriendTabViewController.swift, TTOON/Util/Extension/UIImageView+.swift
- [X]  base branch 꼭 확인하세요!
Issue Number: TTOON-201
- 좋아요 기능 구현했습니다.
- 메뉴 버튼 액션 구현했습니다. (신고하기는 아직 구현하지 않았습니다.)
=> [TN-201] 피드 화면 로직 구현 - 2차

TTOON.xcodeproj/project.pbxproj, TTOON/Data/Repository/Setting/DeleteAccountRepository.swift, TTOON/Domain/Interface/Repository/Setting/DeleteAccountRepositoryProtocol.swift, TTOON/Domain/UseCase/Setting/DeleteAccountUseCase.swift, TTOON/Presentation/Setting/ContactUs/View/CategoryBottomSheetView.swift, TTOON/Presentation/Setting/ContactUs/ViewController/CategoryBottomSheetViewController.swift, TTOON/Presentation/Setting/ContactUs/ViewController/ContactUsViewController.swift, TTOON/Presentation/Setting/DeleteAccount/View/DeleteAccountView.swift, TTOON/Presentation/Setting/DeleteAccount/ViewController/DeleteAccountReasonBottomSheetViewController.swift, TTOON/Presentation/Setting/DeleteAccount/ViewController/DeleteAccountViewController.swift, TTOON/Presentation/Setting/DeleteAccount/ViewModel/DeleteAccountReactor.swift, TTOON/Util/TNCompopnet/BottomSheet/TNSheetCellVer2.swift
- 문의하기, 탈퇴하기 네비게이션 타이틀 적용
- 문의하기, 탈퇴하기 바텀시트 구현 방식 수정 (vc의 sheetPresentationController 활용)
- 문의하기, 탈퇴하기 바텀시트 내 셀 UI Layout 수정 (TNSheetCellVer2 생성)
- 탈퇴하기 화면 유저 닉네임 로드
=> [NO-ISSUE] 문의하기, 탈퇴하기 QA 작업

TTOON.xcodeproj/project.pbxproj, TTOON/Data/API/Toon/ToonAPI.swift, TTOON/Data/DTO/Toon/ToonRequestDTO.swift, TTOON/Data/DTO/Toon/ToonResponseDTO.swift, TTOON/Data/Repository/Toon/ToonRepository.swift, TTOON/Domain/Interface/Repository/Toon/ToonRepositoryProtocol.swift, TTOON/Domain/UseCase/Toon/ToonUseCase.swift
Issue Number: TTOON-211
- 캐릭터 CRUD API 연결을 위해 Data 레이어를 파일 생성/ 코드 추가했습니다.
- 도메인의 경우 파일만 생성해뒀습니다.
- 스크린샷x
=> [TTOON-211] 캐릭터 CRUD 도메인, 데이터 레이어 생성

TTOON.xcodeproj/project.pbxproj, TTOON/Data/DTO/Toon/ToonResponseDTO.swift, TTOON/Data/Keychain/KeychainStorage.swift, TTOON/Data/Repository/Toon/ToonRepository.swift, TTOON/Domain/Entity/Toon/ToonModel.swift, TTOON/Domain/Interface/Repository/Toon/ToonRepositoryProtocol.swift, TTOON/Domain/UseCase/Toon/ToonUseCase.swift, TTOON/Presentation/Toon/CreateToon/View/CharacterPickerBSView.swift, TTOON/Presentation/Toon/CreateToon/ViewController/CharacterPickerBSViewController.swift, TTOON/Presentation/Toon/CreateToon/ViewController/EnterInfoViewController.swift, TTOON/Presentation/Toon/CreateToon/ViewModel/CharacterPickerBSReactor.swift, TTOON/Util/Manager/UserDefaultsManager.swift
Issue Number: TTOON-212
[문서](https://www.notion.so/lyoodong/TTOON-212-11a10412f597804aae32d4061d6df5e6)
- 캐릭터 조회 기능 API 연결
- list, empty, invalid로 상태 분기
- list -> 정상적으로 리스트 조회 && 추가된 캐릭터 있음
- empty -> 정상적으로 리스트 조회 && 추가된 캐릭터 없음
- invalid -> 에러 발생해서 리스트 조회 실패
- 문서 참고
=> [TN-212] 캐릭터 조회(READ) 비지니스 로직 

TTOON.xcodeproj/project.pbxproj, TTOON/Presentation/CustomView/Toon/CreateToon/CharacterPickerTableView.swift, TTOON/Presentation/CustomView/Toon/CreateToon/CharacterPickerTableViewCell.swift, TTOON/Presentation/Toon/CreateToon/View/CharacterEditorScrollView.swift, TTOON/Presentation/Toon/CreateToon/View/CharacterEditorView.swift, TTOON/Presentation/Toon/CreateToon/View/CharacterModifyView.swift, TTOON/Presentation/Toon/CreateToon/View/CompleteToonScrollView.swift, TTOON/Presentation/Toon/CreateToon/ViewController/CharacterAddViewController.swift, TTOON/Presentation/Toon/CreateToon/ViewController/EnterInfoViewController.swift, TTOON/Presentation/Toon/CreateToon/ViewModel/CharacterAddReactor.swift, TTOON/Util/TNCompopnet/TextFiled/TNTextFiled.swift, TTOON/Util/TNCompopnet/TextFiled/TextStatusView.swift
Issue Number: TTOON-213
- 캐릭터 추가화면 UI 레이아웃 수정
- 캐릭터 추가화면 UI 로직 바인딩(글자수 제한, 추가 버튼 활성화)
=> [TN-213] 캐릭터 추가 화면 UI 수정 

TTOON/Data/Repository/Toon/ToonRepository.swift, TTOON/Domain/Entity/Toon/ToonModel.swift, TTOON/Domain/UseCase/Toon/ToonUseCase.swift, TTOON/Presentation/Toon/CreateToon/View/CharacterEditorScrollView.swift, TTOON/Presentation/Toon/CreateToon/ViewController/CharacterAddViewController.swift, TTOON/Presentation/Toon/CreateToon/ViewController/CharacterModifyViewController.swift, TTOON/Presentation/Toon/CreateToon/ViewModel/CharacterAddReactor.swift
Issue Number: TTOON-214
- 캐릭터 추가 API 연동
- '완료' 버튼 클릭 시 추가 API 요청
**주의: 개발 당시에는 응답이 따로 없었는데 지금은 data가 생겼습니다. 그래서 요청을 하면 201이 뜨긴 할건데  decoding에 실패해서 화면이 pop되는 로직은 이어지지 않을 것입니다. 추가는 정상적으로 잘 됩니다. 이 부분은 차후 작업에 개선되어서 차후 PR에 말씀드리겠습니다. 지금은 '요청 성공' 정도만 봐주시면 될 것 같네요.
=> [TN-214] 캐릭터 추가 API 연동 초안

TTOON/Presentation/Toon/CreateToon/ViewModel/CharacterAddReactor.swift
=> [NO-ISSUE] mainCharacterId keychain 관련 코드 제거

TTOON.xcodeproj/project.pbxproj, TTOON/Application/AppDelegate.swift
- Firebase 콘솔 로그 추가 및 GoogleServiceInfo.plist 파일 변경
=> [NO-ISSUE] Firebase 콘솔 로그 추가

TTOON.xcodeproj/project.pbxproj, TTOON/Presentation/Setting/ContactUs/View/ContactUsView.swift, TTOON/Presentation/Setting/DeleteAccount/View/DeleteAccountView.swift
- 기기 대응이 안된 문의하기/탈퇴하기 화면 스크롤뷰 적용
=> [NO-ISSUE] 1차 리젝 대응 - 문의하기, 탈퇴하기 화면 스크롤뷰로 변경

TTOON/Application/AppDelegate.swift, TTOON/Data/DTO/CalendarFeed/FeedDTO.swift, TTOON/Presentation/CustomView/Home/Friend/TableViewProfileInfoView.swift, TTOON/Presentation/Home/Feed/ViewModel/HomeFeedReactor.swift
- 좋아요 리스트 나오지 않는 이슈 (UserInfoDTO의 image Optional 타입으로 변환)
- 피드 첫 로드 시 데이터 없는 경우 대응
=> [NO-ISSUE] 좋아요 리스트 나오지 않는 이슈, 피드에 데이터 없을 때 처리 대응
